name: release

on:
  push:
    branches:
      - fix/release
    tags:
      - v*

jobs:
  release:
    name: release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.17.5"
      - run: scripts/build
      - run: install dist/corral-"$VERSION"-amd64 /usr/local/bin/corral
      - run: corral config --user_id ci --public_key=/dev/null
      - run: corral login --username ${{ github.actor }} --password ${{ secrets.GITHUB_TOKEN }} ghcr.io
      - run: scripts/push-packages
      - uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          files: dist/*
          prerelease: ${{ env.IS_PRERELEASE }}
          generate_release_notes: true
